[build]
  command = "npm run build"  
  publish = "dist"           
  functions = "functions/"
  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[functions]]
  name = "myFunction"
  path = "myFunction.js"
  events = ["http"]
  roues = "/.netlify/functions/myFunction"
